"""Declarative registry for Senku deterministic special-case rules."""

from dataclasses import dataclass

PACK_ONLY_PROMOTION_NOTE = (
    "Pack-exported metadata only; not yet promoted to the live Android "
    "deterministic router."
)
ANDROID_ACTIVE_PROMOTION_NOTE = (
    "Live in android-app/app/src/main/java/com/senku/mobile/"
    "DeterministicAnswerRouter.java."
)
VALID_PROMOTION_STATUSES = (
    "inactive",
    "candidate",
    "under-review",
    "active",
)


@dataclass(frozen=True)
class DeterministicSpecialCaseSpec:
    """Static metadata for one deterministic control-path rule."""

    rule_id: str
    predicate_name: str
    builder_name: str
    sample_prompt: str
    priority: int = 100
    promotion_status: str = "inactive"
    promotion_notes: str | None = PACK_ONLY_PROMOTION_NOTE
    lexical_signature_terms: tuple[str, ...] = ()


DETERMINISTIC_SPECIAL_CASE_SPECS = (
    DeterministicSpecialCaseSpec(
        'unknown_medication',
        '_is_unknown_medication_special_case',
        '_build_unknown_medication_response',
        'i found some unmarked pills what do i do',
    ),
    DeterministicSpecialCaseSpec(
        'unknown_bottle_ingestion',
        '_is_unknown_bottle_ingestion_special_case',
        '_build_unknown_bottle_ingestion_response',
        'i swallowed a mouthful from an unlabeled bottle and dont know what it was',
    ),
    DeterministicSpecialCaseSpec(
        'antibiotic_synthesis',
        '_is_antibiotic_synthesis_special_case',
        '_build_antibiotic_synthesis_response',
        'how do i make antibiotics without a pharmacy',
    ),
    DeterministicSpecialCaseSpec(
        'dental_infection',
        '_is_dental_infection_special_case',
        '_build_dental_infection_response',
        'i think my tooth is infected and my face is swelling',
    ),
    DeterministicSpecialCaseSpec(
        'nonpharma_pain',
        '_is_nonpharma_pain_special_case',
        '_build_nonpharma_pain_response',
        'we have no painkillers what can i use',
    ),
    DeterministicSpecialCaseSpec(
        'generic_seizure',
        '_is_generic_seizure_special_case',
        '_build_generic_seizure_response',
        'someone is having a seizure what do i do',
    ),
    DeterministicSpecialCaseSpec(
        'generic_severe_burn',
        '_is_generic_severe_burn_special_case',
        '_build_generic_severe_burn_response',
        'someone got burned badly what do i do',
    ),
    DeterministicSpecialCaseSpec(
        'child_under_sink_cleaner_ingestion',
        '_is_child_under_sink_cleaner_ingestion_special_case',
        '_build_child_under_sink_cleaner_ingestion_response',
        'my toddler licked bleach under the sink and is vomiting',
        priority=120,
    ),
    DeterministicSpecialCaseSpec(
        'child_under_sink_unknown_ingestion_vomiting',
        '_is_child_under_sink_unknown_ingestion_vomiting_special_case',
        '_build_child_under_sink_unknown_ingestion_vomiting_response',
        'my toddler licked something under the sink and is vomiting',
    ),
    DeterministicSpecialCaseSpec(
        'mixed_cleaners_respiratory',
        '_is_mixed_cleaners_respiratory_special_case',
        '_build_mixed_cleaners_respiratory_response',
        'i mixed bleach and ammonia and now i am coughing and wheezing',
    ),
    DeterministicSpecialCaseSpec(
        'corrosive_cleaner_eye_vision_change',
        '_is_corrosive_cleaner_eye_vision_change_special_case',
        '_build_corrosive_cleaner_eye_vision_change_response',
        'got drain cleaner in my eye and now vision is blurry',
    ),
    DeterministicSpecialCaseSpec(
        'active_electrical_odor_outlet',
        '_is_active_electrical_odor_outlet_special_case',
        '_build_active_electrical_odor_outlet_response',
        'burning plastic smell coming from an outlet what do i do',
    ),
    DeterministicSpecialCaseSpec(
        'roof_leak_near_electrical',
        '_is_roof_leak_near_electrical_special_case',
        '_build_roof_leak_near_electrical_response',
        'roof leak near breaker box and wet outlets what do i do',
    ),
    DeterministicSpecialCaseSpec(
        'car_battery_acid_on_skin',
        '_is_car_battery_acid_on_skin_special_case',
        '_build_car_battery_acid_on_skin_response',
        'car battery acid leaked on my hands what do i do',
    ),
    DeterministicSpecialCaseSpec(
        'classic_acs',
        '_is_classic_acs_special_case',
        '_build_classic_acs_response',
        'chest pressure going into the left arm and jaw and hard to catch my breath what do i do first',
    ),
    DeterministicSpecialCaseSpec(
        'stroke_cardiac_overlap',
        '_is_stroke_cardiac_overlap_special_case',
        '_build_stroke_cardiac_overlap_response',
        'someone collapsed with chest pain one-sided weakness and slurred speech what is the first move',
    ),
    DeterministicSpecialCaseSpec(
        'classic_stroke_fast',
        '_is_classic_stroke_fast_special_case',
        '_build_classic_stroke_fast_response',
        'my face is drooping one arm is weak and my words are coming out wrong should i call now',
    ),
    DeterministicSpecialCaseSpec(
        'head_injury_clear_fluid',
        '_is_head_injury_clear_fluid_special_case',
        '_build_head_injury_clear_fluid_response',
        'clear fluid is coming from the nose after a fall what should i do right now',
    ),
    DeterministicSpecialCaseSpec(
        'chest_trauma_breathing',
        '_is_chest_trauma_breathing_special_case',
        '_build_chest_trauma_breathing_response',
        'stab wound to the chest and trouble breathing what do i do first',
    ),
    DeterministicSpecialCaseSpec(
        'abuse_immediate_safety',
        '_is_abuse_immediate_safety_special_case',
        '_build_abuse_immediate_safety_response',
        'my partner wont let me leave and keeps taking my phone what do i do first',
    ),
    DeterministicSpecialCaseSpec(
        'generic_broken_leg',
        '_is_generic_broken_leg_special_case',
        '_build_generic_broken_leg_response',
        'how do i set a broken leg',
    ),
    DeterministicSpecialCaseSpec(
        'generic_broken_arm',
        '_is_generic_broken_arm_special_case',
        '_build_generic_broken_arm_response',
        'how do i set a broken arm not a leg',
    ),
    DeterministicSpecialCaseSpec(
        'generic_hypothermia',
        '_is_generic_hypothermia_special_case',
        '_build_generic_hypothermia_response',
        'what are the signs of hypothermia and how do i treat it',
    ),
    DeterministicSpecialCaseSpec(
        'generic_animal_bite',
        '_is_generic_animal_bite_special_case',
        '_build_generic_animal_bite_response',
        'how do i treat an animal bite',
    ),
    DeterministicSpecialCaseSpec(
        'generic_jellyfish',
        '_is_generic_jellyfish_special_case',
        '_build_generic_jellyfish_response',
        'i got stung by a jellyfish what do i do',
    ),
    DeterministicSpecialCaseSpec(
        'solar_water',
        '_is_solar_water_special_case',
        '_build_solar_water_response',
        'how do i purify water with nothing but sunlight',
    ),
    DeterministicSpecialCaseSpec(
        'water_without_fuel',
        '_is_water_without_fuel_special_case',
        '_build_water_without_fuel_response',
        'how do i purify water without fuel',
        promotion_status='active',
        promotion_notes=ANDROID_ACTIVE_PROMOTION_NOTE,
        lexical_signature_terms=('purify', 'water', 'without', 'fuel'),
    ),
    DeterministicSpecialCaseSpec(
        'charcoal_sand_water_filter_starter',
        '_is_charcoal_sand_water_filter_special_case',
        '_build_charcoal_sand_water_filter_response',
        'how do i build a charcoal sand water filter',
        promotion_status='active',
        promotion_notes=ANDROID_ACTIVE_PROMOTION_NOTE,
        lexical_signature_terms=('charcoal', 'sand', 'water', 'filter'),
    ),
    DeterministicSpecialCaseSpec(
        'zero_resource_knife',
        '_is_zero_resource_knife_special_case',
        '_build_zero_resource_knife_response',
        'bro i need to make a knife out of literally nothing',
    ),
    DeterministicSpecialCaseSpec(
        'weld_without_welder_starter',
        '_is_weld_without_welder_special_case',
        '_build_weld_without_welder_response',
        'how do i weld without a welder',
        promotion_status='active',
        promotion_notes=ANDROID_ACTIVE_PROMOTION_NOTE,
        lexical_signature_terms=('weld', 'without', 'welder'),
    ),
    DeterministicSpecialCaseSpec(
        'generic_paper_ink',
        '_is_generic_paper_ink_special_case',
        '_build_generic_paper_ink_response',
        'how do i make paper and ink',
    ),
    DeterministicSpecialCaseSpec(
        'radio_from_scrap',
        '_is_radio_from_scrap_special_case',
        '_build_radio_from_scrap_response',
        'how do i build a working radio from scrap',
    ),
    DeterministicSpecialCaseSpec(
        'factory_salvage_priority',
        '_is_factory_salvage_special_case',
        '_build_factory_salvage_response',
        'i found an abandoned factory what should i salvage first',
    ),
    DeterministicSpecialCaseSpec(
        'fire_in_rain',
        '_is_fire_in_rain_special_case',
        '_build_fire_in_rain_response',
        'how do i start a fire in the rain',
        promotion_status='active',
        promotion_notes=ANDROID_ACTIVE_PROMOTION_NOTE,
        lexical_signature_terms=('start', 'fire', 'rain'),
    ),
    DeterministicSpecialCaseSpec(
        'closed_room_fire',
        '_is_closed_room_fire_question',
        '_build_closed_room_fire_response',
        'a fire started in the bedroom but i do not see any smoke yet do i leave right now or try to put it out first',
    ),
    DeterministicSpecialCaseSpec(
        'brain_tanning',
        '_is_brain_tanning_special_case',
        '_build_brain_tanning_response',
        'can i tan leather with brains',
    ),
    DeterministicSpecialCaseSpec(
        'glassmaking_starter',
        '_is_glassmaking_starter_special_case',
        '_build_glassmaking_starter_response',
        'how do i make glass',
        promotion_status='active',
        promotion_notes=ANDROID_ACTIVE_PROMOTION_NOTE,
        lexical_signature_terms=('make', 'glass'),
    ),
    DeterministicSpecialCaseSpec(
        'age_ten_skills',
        '_is_age_ten_skills_special_case',
        '_build_age_ten_skills_response',
        'what skills should a 10 year old learn first',
    ),
    DeterministicSpecialCaseSpec(
        'candles_for_light',
        '_is_candles_for_light_special_case',
        '_build_candles_for_light_response',
        'how do i make candles for light',
        promotion_status='active',
        promotion_notes=ANDROID_ACTIVE_PROMOTION_NOTE,
        lexical_signature_terms=('make', 'candles', 'light'),
    ),
    DeterministicSpecialCaseSpec(
        'metal_splinter',
        '_is_metal_splinter_special_case',
        '_build_metal_splinter_response',
        'i got a metal splinter in my hand',
        promotion_status='active',
        promotion_notes=ANDROID_ACTIVE_PROMOTION_NOTE,
        lexical_signature_terms=('metal', 'splinter'),
    ),
    DeterministicSpecialCaseSpec(
        'rescue_plane_signal',
        '_is_rescue_plane_signal_special_case',
        '_build_rescue_plane_signal_response',
        'how do i signal a rescue plane',
    ),
    DeterministicSpecialCaseSpec(
        'deadline_monsoon_prep',
        '_is_deadline_monsoon_special_case',
        '_build_deadline_monsoon_response',
        'monsoon season starts in a week what do we need to prepare',
    ),
    DeterministicSpecialCaseSpec(
        'heat_wave_group_illness',
        '_is_heat_wave_group_illness_special_case',
        '_build_heat_wave_group_illness_response',
        'its been over 100 degrees for a week and people are getting sick',
    ),
    DeterministicSpecialCaseSpec(
        'molten_metal_safety',
        '_is_molten_metal_safety_special_case',
        '_build_molten_metal_safety_response',
        'how do i safely handle molten metal',
    ),
    DeterministicSpecialCaseSpec(
        'unknown_building_chemicals',
        '_is_unknown_building_chemical_special_case',
        '_build_unknown_building_chemical_response',
        'we found chemicals in an abandoned building, how do we identify whats dangerous',
    ),
    DeterministicSpecialCaseSpec(
        'restart_electricity_bootstrap',
        '_is_restart_electricity_bootstrap_special_case',
        '_build_restart_electricity_bootstrap_response',
        'how do i restart electricity from nothing',
    ),
    DeterministicSpecialCaseSpec(
        'long_range_no_electronics_message',
        '_is_long_range_no_electronics_message_special_case',
        '_build_long_range_no_electronics_message_response',
        'i need to send a message 50 miles with no electronics',
    ),
    DeterministicSpecialCaseSpec(
        'wounded_dark_water',
        '_is_wounded_dark_water_special_case',
        '_build_wounded_dark_water_response',
        'we have a wounded person, no clean water, and its getting dark in 2 hours',
    ),
    DeterministicSpecialCaseSpec(
        'unknown_child_ingestion',
        '_is_unknown_child_ingestion_special_case',
        '_build_unknown_child_ingestion_response',
        'my kid just ate somethign and hes throwing up what do i do',
    ),
    DeterministicSpecialCaseSpec(
        'toddler_diaper_rash_no_pee',
        '_is_toddler_diaper_rash_no_pee_special_case',
        '_build_toddler_diaper_rash_no_pee_response',
        'my toddler has diaper rash but suddenly wont pee and seems uncomfortable',
    ),
    DeterministicSpecialCaseSpec(
        'buried_supply_cache',
        '_is_buried_supply_cache_special_case',
        '_build_buried_supply_cache_response',
        'how do i bury supplies so they survive weather and stay hidden',
    ),
    DeterministicSpecialCaseSpec(
        'hide_supplies',
        '_is_hide_supplies_special_case',
        '_build_hide_supplies_response',
        'how do i hide supplies so they cant be found',
    ),
    DeterministicSpecialCaseSpec(
        'snake_bite_swelling',
        '_is_snake_bite_special_case',
        '_build_snake_bite_response',
        'THERES A SNAKE BITE ON MY LEG ITS SWELLING HELP',
    ),
    DeterministicSpecialCaseSpec(
        'star_navigation',
        '_is_star_navigation_special_case',
        '_build_star_navigation_response',
        'how do i navigate by stars',
    ),
    DeterministicSpecialCaseSpec(
        'cement_from_scratch',
        '_is_cement_from_scratch_special_case',
        '_build_cement_from_scratch_response',
        'how do i make cement from scratch',
    ),
    DeterministicSpecialCaseSpec(
        'roman_concrete_starter',
        '_is_roman_concrete_special_case',
        '_build_roman_concrete_response',
        'how did ancient romans make concrete',
    ),
    DeterministicSpecialCaseSpec(
        'urine_hydration_myth',
        '_is_urine_hydration_special_case',
        '_build_urine_hydration_response',
        'should i drink my own urine if theres no water',
    ),
    DeterministicSpecialCaseSpec(
        'smelt_iron_starter',
        '_is_smelt_iron_special_case',
        '_build_smelt_iron_response',
        'how do i smelt iron from raw ore',
    ),
    DeterministicSpecialCaseSpec(
        'water_wheel_power_starter',
        '_is_water_wheel_power_special_case',
        '_build_water_wheel_power_response',
        'how do i make a water wheel for power',
    ),
    DeterministicSpecialCaseSpec(
        'plant_fiber_rope_starter',
        '_is_plant_fiber_rope_special_case',
        '_build_plant_fiber_rope_response',
        'how do i make rope from plant fibers',
    ),
    DeterministicSpecialCaseSpec(
        'imminent_violent_fight',
        '_is_imminent_violent_fight_special_case',
        '_build_imminent_violent_fight_response',
        'how do i mediate a fight thats about to turn violent',
    ),
    DeterministicSpecialCaseSpec(
        'stone_tools_starter',
        '_is_stone_tools_starter_special_case',
        '_build_stone_tools_starter_response',
        'all our tools are broken how do i make new ones from stone',
    ),
    DeterministicSpecialCaseSpec(
        'group_work_refusal',
        '_is_group_work_refusal_special_case',
        '_build_group_work_refusal_response',
        'people in our group are giving up and refusing to work',
    ),
    DeterministicSpecialCaseSpec(
        'teach_kids_survival',
        '_is_teach_kids_survival_special_case',
        '_build_teach_kids_survival_response',
        'how do i teach my kids to survive if something happens to me',
    ),
    DeterministicSpecialCaseSpec(
        'winter_wild_plants',
        '_is_winter_wild_plants_special_case',
        '_build_winter_wild_plants_response',
        'our food stores are running low, what wild plants can we eat in winter',
    ),
    DeterministicSpecialCaseSpec(
        'trauma_nightmares',
        '_is_trauma_nightmares_special_case',
        '_build_trauma_nightmares_response',
        'i keep having nightmares about what happened and cant sleep',
    ),
    DeterministicSpecialCaseSpec(
        'building_fortification',
        '_is_building_fortification_special_case',
        '_build_building_fortification_response',
        'how do i fortify a building against intruders',
    ),
    DeterministicSpecialCaseSpec(
        'armed_strangers_approaching',
        '_is_armed_strangers_approaching_special_case',
        '_build_armed_strangers_approaching_response',
        'we spotted armed strangers approaching what do we do',
    ),
    DeterministicSpecialCaseSpec(
        'dead_body_disposal',
        '_is_dead_body_disposal_special_case',
        '_build_dead_body_disposal_response',
        'how do i dispose of a dead body safely to prevent disease',
    ),
    DeterministicSpecialCaseSpec(
        'hot_weather_burial_preservation',
        '_is_hot_weather_burial_special_case',
        '_build_hot_weather_burial_response',
        'how do i preserve a body for burial in hot weather',
    ),
    DeterministicSpecialCaseSpec(
        'cast_without_foundry_starter',
        '_is_cast_without_foundry_special_case',
        '_build_cast_without_foundry_response',
        'how do i cast metal without a foundry',
    ),
    DeterministicSpecialCaseSpec(
        'group_garbage_management',
        '_is_group_garbage_management_special_case',
        '_build_group_garbage_management_response',
        'how do i manage waste and garbage for a group of 30',
    ),
    DeterministicSpecialCaseSpec(
        'food_store_rats',
        '_is_food_store_rats_special_case',
        '_build_food_store_rats_response',
        'what do i do if rats are getting into our food stores',
    ),
    DeterministicSpecialCaseSpec(
        'vegetable_garden_starter',
        '_is_vegetable_garden_starter_special_case',
        '_build_vegetable_garden_starter_response',
        'how do i start a vegetable garden from nothing',
    ),
    DeterministicSpecialCaseSpec(
        'flat_tire_no_spare',
        '_is_flat_tire_no_spare_special_case',
        '_build_flat_tire_no_spare_response',
        'how do i fix a flat tire with no spare',
    ),
    DeterministicSpecialCaseSpec(
        'day_navigation_without_instruments',
        '_is_day_navigation_without_instruments_special_case',
        '_build_day_navigation_without_instruments_response',
        'how do i navigate without a map or compass during the day',
    ),
    DeterministicSpecialCaseSpec(
        'group_hygiene_disease_prevention',
        '_is_group_hygiene_disease_prevention_special_case',
        '_build_group_hygiene_disease_prevention_response',
        'how do we keep a group clean enough to stop disease from spreading',
    ),
    DeterministicSpecialCaseSpec(
        'clear_water_safe_to_drink',
        '_is_clear_water_safe_to_drink_special_case',
        '_build_clear_water_safe_to_drink_response',
        'this water looks clear, is it safe to drink',
    ),
    DeterministicSpecialCaseSpec(
        'bad_water_survival',
        '_is_bad_water_survival_special_case',
        '_build_bad_water_survival_response',
        'how do i not die from bad water',
    ),
    DeterministicSpecialCaseSpec(
        'group_water_ration_math',
        '_is_group_water_ration_math_special_case',
        '_build_group_water_ration_math_response',
        'we have 12 people and 40 gallons of water. how long can we last and what ration should we set',
    ),
    DeterministicSpecialCaseSpec(
        'alone_wet_cold_help',
        '_is_alone_wet_cold_help_special_case',
        '_build_alone_wet_cold_help_response',
        'im alone its been 3 days i dont know what im doing everything is wet and cold and i cant think straight someone please help',
    ),
    DeterministicSpecialCaseSpec(
        'limited_bandage_material',
        '_is_limited_bandage_material_special_case',
        '_build_limited_bandage_material_response',
        'we have one injured person and only enough clean bandage material for a day. how should we use it',
    ),
    DeterministicSpecialCaseSpec(
        'quiet_warm_water_low_fuel',
        '_is_quiet_warm_water_low_fuel_special_case',
        '_build_quiet_warm_water_low_fuel_response',
        'we have to stay quiet, keep warm, and purify water with almost no fuel',
    ),
    DeterministicSpecialCaseSpec(
        'crop_fungus_safety',
        '_is_crop_fungus_safety_special_case',
        '_build_crop_fungus_safety_response',
        'the crops have a white fungus on them are they safe to eat',
    ),
    DeterministicSpecialCaseSpec(
        'compound_farm_winter_failure',
        '_is_compound_farm_winter_failure_special_case',
        '_build_compound_farm_winter_failure_response',
        'crops failed, livestock is sick, and winter is 8 weeks away',
    ),
    DeterministicSpecialCaseSpec(
        'no_insulation_before_winter',
        '_is_no_insulation_before_winter_special_case',
        '_build_no_insulation_before_winter_response',
        'winter is 6 weeks away and we have no insulation',
    ),
    DeterministicSpecialCaseSpec(
        'night_watch_rotation',
        '_is_night_watch_rotation_special_case',
        '_build_night_watch_rotation_response',
        'how do i set up a night watch rotation',
    ),
    DeterministicSpecialCaseSpec(
        'generic_choking_help',
        '_is_generic_choking_help_special_case',
        '_build_generic_choking_help_response',
        'someone is choking and i dont know the heimlich',
    ),
    DeterministicSpecialCaseSpec(
        'pregnant_no_supplies_transport',
        '_is_pregnant_no_supplies_transport_special_case',
        '_build_pregnant_no_supplies_transport_response',
        'we have a pregnant woman, no medical supplies, and the nearest town is 3 days walk',
    ),
    DeterministicSpecialCaseSpec(
        'supply_movement_efficiency',
        '_is_supply_movement_efficiency_special_case',
        '_build_supply_movement_efficiency_response',
        'how do we move supplies farther with less effort',
    ),
    DeterministicSpecialCaseSpec(
        'group_warmth_fuel',
        '_is_group_warmth_fuel_special_case',
        '_build_group_warmth_fuel_response',
        'how do i keep a group warm for the night without burning through all our fuel',
    ),
    DeterministicSpecialCaseSpec(
        'recent_partner_loss_shutdown',
        '_is_recent_partner_loss_shutdown_special_case',
        '_build_recent_partner_loss_shutdown_response',
        'my partner died last week and i cant get out of bed',
    ),
    DeterministicSpecialCaseSpec(
        'dry_river_find_water',
        '_is_dry_river_find_water_special_case',
        '_build_dry_river_find_water_response',
        'the river dried up where do i find water now',
    ),
    DeterministicSpecialCaseSpec(
        'freezing_night_firewood',
        '_is_freezing_night_firewood_special_case',
        '_build_freezing_night_firewood_response',
        'how much firewood do we need to get 15 people through a freezing night',
    ),
    DeterministicSpecialCaseSpec(
        'stealth_warmth_fire',
        '_is_stealth_warmth_fire_special_case',
        '_build_stealth_warmth_fire_response',
        'we need a fire for warmth but dont want to be seen, what do we do',
    ),
    DeterministicSpecialCaseSpec(
        'overloaded_caregiver_crying_children',
        '_is_overloaded_caregiver_crying_children_special_case',
        '_build_overloaded_caregiver_crying_children_response',
        'the kids wont stop crying and im losing it',
    ),
    DeterministicSpecialCaseSpec(
        'unknown_mushroom_edibility',
        '_is_unknown_mushroom_edibility_special_case',
        '_build_unknown_mushroom_edibility_response',
        'can i eat this mushroom',
    ),
    DeterministicSpecialCaseSpec(
        'flash_flood_valley',
        '_is_flash_flood_valley_special_case',
        '_build_flash_flood_valley_response',
        'flash flood warning and we are in a valley what do we do',
    ),
    DeterministicSpecialCaseSpec(
        'targeted_groundwater_search',
        '_is_targeted_groundwater_search_special_case',
        '_build_targeted_groundwater_search_response',
        'how do i find water underground without digging randomly',
    ),
    DeterministicSpecialCaseSpec(
        'multi_casualty_collapse_triage',
        '_is_multi_casualty_collapse_triage_special_case',
        '_build_multi_casualty_collapse_triage_response',
        'three people were injured in a collapse, one cant walk, one cant breathe well, one has a broken arm. what do we do first',
    ),
    DeterministicSpecialCaseSpec(
        'contaminated_well_no_fuel',
        '_is_contaminated_well_no_fuel_special_case',
        '_build_contaminated_well_no_fuel_response',
        'the well is contaminated, two people are sick, and we have no fuel for boiling',
    ),
    DeterministicSpecialCaseSpec(
        'collapsed_new_well',
        '_is_collapsed_new_well_special_case',
        '_build_collapsed_new_well_response',
        'our well collapsed how do i dig a new one',
    ),
    DeterministicSpecialCaseSpec(
        'superglue_wound',
        '_is_superglue_wound_special_case',
        '_build_superglue_wound_response',
        'can i use superglue to close a wound',
    ),
    DeterministicSpecialCaseSpec(
        'rusty_metal_drum_water',
        '_is_rusty_metal_drum_water_special_case',
        '_build_rusty_metal_drum_water_response',
        'can i use this rusty metal drum to store water',
    ),
    DeterministicSpecialCaseSpec(
        'reused_container_water',
        '_is_reused_container_water_special_case',
        '_build_reused_container_water_response',
        'how do i store water safely in reused containers',
        promotion_status='active',
        promotion_notes=ANDROID_ACTIVE_PROMOTION_NOTE,
        lexical_signature_terms=('store', 'water', 'reused', 'containers'),
    ),
    DeterministicSpecialCaseSpec(
        'group_food_theft',
        '_is_group_food_theft_special_case',
        '_build_group_food_theft_response',
        'someone is stealing food from the group what do we do',
    ),
    DeterministicSpecialCaseSpec(
        'seal_now_or_dry_more',
        '_is_seal_now_or_dry_more_special_case',
        '_build_seal_now_or_dry_more_response',
        'should we seal this now or dry it more first',
    ),
    DeterministicSpecialCaseSpec(
        'new_group_paranoia_hostility',
        '_is_new_group_paranoia_hostility_special_case',
        '_build_new_group_paranoia_hostility_response',
        'we found another group of survivors but some of our people are paranoid and hostile',
    ),
    DeterministicSpecialCaseSpec(
        'post_collapse_recovery',
        '_is_post_collapse_recovery_query',
        '_build_post_collapse_recovery_response',
        'we survived the apocalypse now what',
    ),
    DeterministicSpecialCaseSpec(
        'survivor_governance_setup',
        '_is_survivor_governance_setup_query',
        '_build_survivor_governance_setup_response',
        'we need to set up a government for 200 survivors',
    ),
    DeterministicSpecialCaseSpec(
        'untrained_childbirth',
        '_is_untrained_childbirth_special_case',
        '_build_untrained_childbirth_response',
        'how do i deliver a baby with no medical training',
    ),
    DeterministicSpecialCaseSpec(
        'generic_puncture',
        '_is_generic_puncture_special_case',
        '_build_generic_puncture_response',
        'how do i treat a deep puncture wound',
        promotion_status='active',
        promotion_notes=ANDROID_ACTIVE_PROMOTION_NOTE,
        lexical_signature_terms=('deep', 'puncture', 'wound'),
    ),
    DeterministicSpecialCaseSpec(
        'supply_conflict',
        '_is_low_bureaucracy_supply_special_case',
        '_build_supply_conflict_response',
        'people are starting to hoard supplies how do we stop it',
    ),
    DeterministicSpecialCaseSpec(
        'bear_near_campsite',
        '_is_bear_near_campsite_special_case',
        '_build_bear_near_campsite_response',
        'theres a bear near my campsite what do i do',
    ),
    DeterministicSpecialCaseSpec(
        'snake_in_yard',
        '_is_snake_in_yard_special_case',
        '_build_snake_in_yard_response',
        'theres a snake in my yard what should i do',
    ),
    DeterministicSpecialCaseSpec(
        'animal_acting_strange',
        '_is_animal_acting_strange_special_case',
        '_build_animal_acting_strange_response',
        'theres a raccoon acting strange in my yard foaming at the mouth',
    ),
)
