"""Declarative registry for Senku deterministic special-case rules."""

from dataclasses import dataclass

PACK_ONLY_PROMOTION_NOTE = (
    "Pack-exported metadata only; not yet promoted to the live Android "
    "deterministic router."
)
ANDROID_ACTIVE_PROMOTION_NOTE = (
    "Live in android-app/app/src/main/java/com/senku/mobile/"
    "DeterministicAnswerRouter.java."
)
VALID_PROMOTION_STATUSES = (
    "inactive",
    "candidate",
    "under-review",
    "active",
)


@dataclass(frozen=True)
class DeterministicSpecialCaseSpec:
    """Static metadata for one deterministic control-path rule."""

    rule_id: str
    predicate_name: str
    builder_name: str
    sample_prompt: str
    priority: int = 100
    promotion_status: str = "inactive"
    promotion_notes: str | None = PACK_ONLY_PROMOTION_NOTE
    lexical_signature_terms: tuple[str, ...] = ()


DETERMINISTIC_SPECIAL_CASE_SPECS = (
    DeterministicSpecialCaseSpec(
        'unknown_medication',
        '_is_unknown_medication_special_case',
        '_build_unknown_medication_response',
        'i found some unmarked pills what do i do',
    ),
    DeterministicSpecialCaseSpec(
        'unknown_bottle_ingestion',
        '_is_unknown_bottle_ingestion_special_case',
        '_build_unknown_bottle_ingestion_response',
        'i swallowed a mouthful from an unlabeled bottle and dont know what it was',
    ),
    DeterministicSpecialCaseSpec(
        'antibiotic_synthesis',
        '_is_antibiotic_synthesis_special_case',
        '_build_antibiotic_synthesis_response',
        'how do i make antibiotics without a pharmacy',
    ),
    DeterministicSpecialCaseSpec(
        'dental_infection',
        '_is_dental_infection_special_case',
        '_build_dental_infection_response',
        'i think my tooth is infected and my face is swelling',
    ),
    DeterministicSpecialCaseSpec(
        'nonpharma_pain',
        '_is_nonpharma_pain_special_case',
        '_build_nonpharma_pain_response',
        'we have no painkillers what can i use',
    ),
    DeterministicSpecialCaseSpec(
        'generic_seizure',
        '_is_generic_seizure_special_case',
        '_build_generic_seizure_response',
        'someone is having a seizure what do i do',
    ),
    DeterministicSpecialCaseSpec(
        'seizure_syncope_panic_withdrawal_triage',
        '_is_seizure_syncope_panic_withdrawal_triage_special_case',
        '_build_seizure_syncope_panic_withdrawal_triage_response',
        'i need to tell whether this is seizure syncope withdrawal or panic what matters first',
        priority=85,
    ),
    DeterministicSpecialCaseSpec(
        'overdose_toxidrome_airway',
        '_is_overdose_toxidrome_airway_special_case',
        '_build_overdose_toxidrome_airway_response',
        'they mixed pills and alcohol and are hard to wake up what matters first',
        priority=95,
    ),
    DeterministicSpecialCaseSpec(
        'stimulant_toxidrome_emergency',
        '_is_stimulant_toxidrome_emergency_special_case',
        '_build_stimulant_toxidrome_emergency_response',
        'they used stimulants and now have chest pain and paranoia what matters first',
        priority=105,
    ),
    DeterministicSpecialCaseSpec(
        'serotonin_syndrome_emergency',
        '_is_serotonin_syndrome_special_case',
        '_build_serotonin_syndrome_emergency_response',
        'started a new antidepressant combo and now i am shaking sweaty and my legs keep jerking',
        priority=96,
        lexical_signature_terms=('antidepressant', 'clonus', 'fever'),
    ),
    DeterministicSpecialCaseSpec(
        'diabetic_glucose_emergency',
        '_is_diabetic_glucose_emergency_special_case',
        '_build_diabetic_glucose_emergency_response',
        'they are diabetic sweaty shaky and acting drunk what matters first',
        priority=96,
    ),
    DeterministicSpecialCaseSpec(
        'infection_delirium_danger',
        '_is_infection_delirium_danger_special_case',
        '_build_infection_delirium_danger_response',
        'they have a high fever and are not making sense what matters first',
        priority=89,
    ),
    DeterministicSpecialCaseSpec(
        'respiratory_infection_distress_emergency',
        '_is_respiratory_infection_distress_emergency_special_case',
        '_build_respiratory_infection_distress_emergency_response',
        'chest infection with fever and breathing so hard i cannot say full sentences',
        priority=93,
        lexical_signature_terms=('cough', 'fever', 'breathing'),
    ),
    DeterministicSpecialCaseSpec(
        'meningitis_rash_emergency',
        '_is_meningitis_rash_emergency_query',
        '_build_meningitis_rash_emergency_response',
        'fever stiff neck and a purple rash that does not fade when pressed',
        priority=91,
        lexical_signature_terms=('fever', 'purple rash', 'stiff neck'),
    ),
    DeterministicSpecialCaseSpec(
        'heat_illness_emergency',
        '_is_heat_illness_emergency_special_case',
        '_build_heat_illness_emergency_response',
        'they stopped sweating on a hot day and are getting confused what matters first',
        priority=92,
    ),
    DeterministicSpecialCaseSpec(
        'gi_bleed_emergency',
        '_is_gi_bleed_emergency_special_case',
        '_build_gi_bleed_emergency_response',
        'they vomited something that looks like coffee grounds what matters first',
        priority=94,
    ),
    DeterministicSpecialCaseSpec(
        'surgical_abdomen_emergency',
        '_is_surgical_abdomen_emergency_query',
        '_build_surgical_abdomen_emergency_response',
        'right lower belly pain with fever and nausea and it hurts to walk',
        priority=93,
    ),
    DeterministicSpecialCaseSpec(
        'blunt_abdominal_trauma_internal_bleeding',
        '_is_blunt_abdominal_trauma_internal_bleeding_special_case',
        '_build_blunt_abdominal_trauma_internal_bleeding_response',
        'belly pain after trauma with lightheadedness and fast heartbeat',
        priority=97,
        lexical_signature_terms=('trauma', 'belly pain', 'lightheaded'),
    ),
    DeterministicSpecialCaseSpec(
        'severe_dehydration_gi_emergency',
        '_is_severe_dehydration_gi_emergency_special_case',
        '_build_severe_dehydration_gi_emergency_response',
        'diarrhea all day and now too weak to stand and barely peeing',
        priority=92,
    ),
    DeterministicSpecialCaseSpec(
        'active_labor_delivery_emergency',
        '_is_active_labor_delivery_emergency_special_case',
        '_build_active_labor_delivery_emergency_response',
        'baby is crowning at home and there is no time to get anywhere',
        priority=108,
    ),
    DeterministicSpecialCaseSpec(
        'postpartum_hemorrhage_emergency',
        '_is_postpartum_hemorrhage_emergency_special_case',
        '_build_postpartum_hemorrhage_emergency_response',
        'delivered the baby an hour ago and now soaking pads and feeling faint',
        priority=109,
    ),
    DeterministicSpecialCaseSpec(
        'generic_severe_burn',
        '_is_generic_severe_burn_special_case',
        '_build_generic_severe_burn_response',
        'someone got burned badly what do i do',
    ),
    DeterministicSpecialCaseSpec(
        'active_drowning_rescue',
        '_is_active_drowning_rescue_special_case',
        '_build_active_drowning_rescue_response',
        'someone is drowning right now what do i do first',
        priority=120,
    ),
    DeterministicSpecialCaseSpec(
        'post_rescue_drowning_breathing',
        '_is_post_rescue_drowning_breathing_special_case',
        '_build_post_rescue_drowning_breathing_response',
        'they seemed okay after being pulled from the water but now they are coughing and short of breath',
        priority=130,
    ),
    DeterministicSpecialCaseSpec(
        'child_under_sink_cleaner_ingestion',
        '_is_child_under_sink_cleaner_ingestion_special_case',
        '_build_child_under_sink_cleaner_ingestion_response',
        'my toddler licked bleach under the sink and is vomiting',
        priority=120,
    ),
    DeterministicSpecialCaseSpec(
        'child_under_sink_unknown_ingestion_vomiting',
        '_is_child_under_sink_unknown_ingestion_vomiting_special_case',
        '_build_child_under_sink_unknown_ingestion_vomiting_response',
        'my toddler licked something under the sink and is vomiting',
    ),
    DeterministicSpecialCaseSpec(
        'button_battery_ingestion_emergency',
        '_is_button_battery_ingestion_emergency_special_case',
        '_build_button_battery_ingestion_emergency_response',
        'toddler swallowed a hearing aid battery and now keeps drooling',
        priority=124,
        lexical_signature_terms=('battery', 'swallowed'),
    ),
    DeterministicSpecialCaseSpec(
        'hydrocarbon_ingestion_aspiration_emergency',
        '_is_hydrocarbon_ingestion_aspiration_emergency_special_case',
        '_build_hydrocarbon_ingestion_aspiration_emergency_response',
        'toddler drank lamp oil and coughed right away',
        priority=122,
    ),
    DeterministicSpecialCaseSpec(
        'industrial_chemical_smell_boundary',
        '_is_industrial_chemical_smell_boundary_query',
        '_build_industrial_chemical_smell_boundary_response',
        'a chemical smells wrong and may be part of an industrial process do we stay in chemistry fundamentals or hand off immediately',
    ),
    DeterministicSpecialCaseSpec(
        'mixed_cleaners_respiratory',
        '_is_mixed_cleaners_respiratory_special_case',
        '_build_mixed_cleaners_respiratory_response',
        'i mixed bleach and ammonia and now i am coughing and wheezing',
    ),
    DeterministicSpecialCaseSpec(
        'chemical_fumes_panic_respiratory',
        '_is_chemical_fumes_panic_respiratory_special_case',
        '_build_chemical_fumes_panic_respiratory_response',
        'i cannot tell if this is a panic attack or chemical fumes what matters first',
        priority=90,
    ),
    DeterministicSpecialCaseSpec(
        'corrosive_cleaner_eye_vision_change',
        '_is_corrosive_cleaner_eye_vision_change_special_case',
        '_build_corrosive_cleaner_eye_vision_change_response',
        'got drain cleaner in my eye and now vision is blurry',
    ),
    DeterministicSpecialCaseSpec(
        'eye_globe_injury_emergency',
        '_is_eye_globe_injury_query',
        '_build_eye_globe_injury_response',
        'metal chip flew into my eye while grinding and it still feels stuck',
        priority=95,
    ),
    DeterministicSpecialCaseSpec(
        'retinal_detachment_eye_emergency',
        '_is_retinal_detachment_eye_emergency_special_case',
        '_build_retinal_detachment_eye_emergency_response',
        'sudden flashes and floaters then a dark curtain over one eye',
        priority=94,
        lexical_signature_terms=('one eye', 'vision loss', 'floaters'),
    ),
    DeterministicSpecialCaseSpec(
        'contact_lens_corneal_infection_emergency',
        '_is_contact_lens_corneal_infection_emergency_special_case',
        '_build_contact_lens_corneal_infection_emergency_response',
        'slept in contact lenses and now one eye hurts badly and hates light',
        priority=93,
        lexical_signature_terms=('contact lens', 'red eye', 'light sensitivity'),
    ),
    DeterministicSpecialCaseSpec(
        'active_electrical_odor_outlet',
        '_is_active_electrical_odor_outlet_special_case',
        '_build_active_electrical_odor_outlet_response',
        'burning plastic smell coming from an outlet what do i do',
    ),
    DeterministicSpecialCaseSpec(
        'electrical_injury_red_flag',
        '_is_electrical_injury_red_flag_special_case',
        '_build_electrical_injury_red_flag_response',
        'shocked by house current and passed out for a second but only have a small burn',
        priority=104,
        lexical_signature_terms=('electrical shock', 'passed out', 'small burn'),
    ),
    DeterministicSpecialCaseSpec(
        'roof_leak_near_electrical',
        '_is_roof_leak_near_electrical_special_case',
        '_build_roof_leak_near_electrical_response',
        'roof leak near breaker box and wet outlets what do i do',
    ),
    DeterministicSpecialCaseSpec(
        'car_battery_acid_on_skin',
        '_is_car_battery_acid_on_skin_special_case',
        '_build_car_battery_acid_on_skin_response',
        'car battery acid leaked on my hands what do i do',
    ),
    DeterministicSpecialCaseSpec(
        'classic_acs',
        '_is_classic_acs_special_case',
        '_build_classic_acs_response',
        'chest pressure going into the left arm and jaw and hard to catch my breath what do i do first',
    ),
    DeterministicSpecialCaseSpec(
        'exertional_syncope_chest_emergency',
        '_is_exertional_syncope_chest_emergency_special_case',
        '_build_exertional_syncope_chest_emergency_response',
        'brief blackout during exertion with chest tightness and shortness of breath',
        priority=93,
    ),
    DeterministicSpecialCaseSpec(
        'stroke_cardiac_overlap',
        '_is_stroke_cardiac_overlap_special_case',
        '_build_stroke_cardiac_overlap_response',
        'someone collapsed with chest pain one-sided weakness and slurred speech what is the first move',
    ),
    DeterministicSpecialCaseSpec(
        'panic_hyperventilation_tingling',
        '_is_panic_hyperventilation_tingling_special_case',
        '_build_panic_hyperventilation_tingling_response',
        'my heart is racing and my hands are tingling after hyperventilating what do i do first',
        priority=80,
    ),
    DeterministicSpecialCaseSpec(
        'respiratory_distress_panic_overlap',
        '_is_respiratory_distress_panic_overlap_special_case',
        '_build_respiratory_distress_panic_overlap_response',
        'my rescue inhaler is not helping and i am panicking what matters first',
        priority=75,
    ),
    DeterministicSpecialCaseSpec(
        'asthma_severe_respiratory_distress',
        '_is_asthma_severe_respiratory_distress_special_case',
        '_build_asthma_severe_respiratory_distress_response',
        'using the inhaler over and over and now the chest is nearly silent',
        priority=92,
        lexical_signature_terms=('asthma', 'silent chest', 'inhaler'),
    ),
    DeterministicSpecialCaseSpec(
        'upper_airway_swelling_danger',
        '_is_upper_airway_swelling_danger_special_case',
        '_build_upper_airway_swelling_danger_response',
        'i hear a harsh noisy breath and they look like their throat is closing what matters first',
        priority=88,
    ),
    DeterministicSpecialCaseSpec(
        'deep_throat_airway_infection_emergency',
        '_is_deep_throat_airway_infection_emergency_special_case',
        '_build_deep_throat_airway_infection_emergency_response',
        'throat pain and muffled hot potato voice with drooling',
        priority=89,
    ),
    DeterministicSpecialCaseSpec(
        'facial_swelling_anxiety_screen',
        '_is_facial_swelling_anxiety_screen_special_case',
        '_build_facial_swelling_anxiety_screen_response',
        'their face is swelling and they think it is anxiety because breathing is still okay what do i do first',
        priority=87,
    ),
    DeterministicSpecialCaseSpec(
        'classic_stroke_fast',
        '_is_classic_stroke_fast_special_case',
        '_build_classic_stroke_fast_response',
        'my face is drooping one arm is weak and my words are coming out wrong should i call now',
    ),
    DeterministicSpecialCaseSpec(
        'hematuria_urgent',
        '_is_hematuria_query',
        '_build_hematuria_urgent_response',
        'blood in the urine without fever when is this urgent',
    ),
    DeterministicSpecialCaseSpec(
        'kidney_infection_urosepsis_emergency',
        '_is_kidney_infection_urosepsis_emergency_special_case',
        '_build_kidney_infection_urosepsis_emergency_response',
        'burning pee turned into flank pain fever and confusion tonight',
        lexical_signature_terms=('flank pain', 'fever', 'urinary symptoms'),
    ),
    DeterministicSpecialCaseSpec(
        'ectopic_pregnancy_emergency',
        '_is_ectopic_pregnancy_emergency_special_case',
        '_build_ectopic_pregnancy_emergency_response',
        'early pregnancy spotting and one-sided lower belly pain and shoulder pain',
        priority=101,
        lexical_signature_terms=('pregnant', 'one-sided pain', 'dizziness'),
    ),
    DeterministicSpecialCaseSpec(
        'late_pregnancy_hypertensive_emergency',
        '_is_late_pregnancy_hypertensive_emergency_special_case',
        '_build_late_pregnancy_hypertensive_emergency_response',
        '34 weeks pregnant with severe headache and flashing lights in vision',
        priority=102,
        lexical_signature_terms=('pregnant', 'severe headache', 'vision'),
    ),
    DeterministicSpecialCaseSpec(
        'major_blood_loss_shock',
        '_is_major_blood_loss_shock_query',
        '_build_major_blood_loss_shock_response',
        'they are pale and dizzy after losing blood what should i do first',
        priority=85,
    ),
    DeterministicSpecialCaseSpec(
        'anaphylaxis_red_zone',
        '_is_anaphylaxis_red_zone_special_case',
        '_build_anaphylaxis_red_zone_response',
        'bee sting and now the throat feels tight what do i do first',
        priority=90,
    ),
    DeterministicSpecialCaseSpec(
        'medication_allergy_swelling',
        '_is_medication_allergy_swelling_special_case',
        '_build_medication_allergy_swelling_response',
        'facial swelling after taking amoxicillin do i stop and call now',
        priority=95,
    ),
    DeterministicSpecialCaseSpec(
        'medicine_hives_skin_only',
        '_is_medicine_hives_skin_only_special_case',
        '_build_medicine_hives_skin_only_response',
        'hives after a new medicine is this anaphylaxis or a mild rash',
    ),
    DeterministicSpecialCaseSpec(
        'soap_rash_breathing_fine',
        '_is_soap_rash_breathing_fine_special_case',
        '_build_soap_rash_breathing_fine_response',
        'itchy rash after soap but breathing is fine do i still need emergency care',
    ),
    DeterministicSpecialCaseSpec(
        'head_injury_clear_fluid',
        '_is_head_injury_clear_fluid_special_case',
        '_build_head_injury_clear_fluid_response',
        'clear fluid is coming from the nose after a fall what should i do right now',
        priority=85,
    ),
    DeterministicSpecialCaseSpec(
        'adult_head_injury_red_flag',
        '_is_adult_head_injury_red_flag_special_case',
        '_build_adult_head_injury_red_flag_response',
        'i hit my head and keep vomiting what do i do first',
    ),
    DeterministicSpecialCaseSpec(
        'chest_trauma_breathing',
        '_is_chest_trauma_breathing_special_case',
        '_build_chest_trauma_breathing_response',
        'stab wound to the chest and trouble breathing what do i do first',
    ),
    DeterministicSpecialCaseSpec(
        'abuse_immediate_safety',
        '_is_abuse_immediate_safety_special_case',
        '_build_abuse_immediate_safety_response',
        'my partner wont let me leave and keeps taking my phone what do i do first',
    ),
    DeterministicSpecialCaseSpec(
        'generic_broken_leg',
        '_is_generic_broken_leg_special_case',
        '_build_generic_broken_leg_response',
        'how do i set a broken leg',
    ),
    DeterministicSpecialCaseSpec(
        'limb_fracture_neurovascular_emergency',
        '_is_limb_fracture_neurovascular_emergency_special_case',
        '_build_limb_fracture_neurovascular_emergency_response',
        'broken arm looks bent wrong and the fingers are numb and pale',
        priority=112,
    ),
    DeterministicSpecialCaseSpec(
        'crush_compartment_syndrome_emergency',
        '_is_crush_compartment_query',
        '_build_crush_compartment_syndrome_emergency_response',
        'pain out of proportion and the leg is getting tighter after a crush injury',
        priority=114,
        lexical_signature_terms=('crush', 'pain', 'tight'),
    ),
    DeterministicSpecialCaseSpec(
        'spinal_trauma_neurologic_emergency',
        '_is_spinal_trauma_neurologic_emergency_special_case',
        '_build_spinal_trauma_neurologic_emergency_response',
        'fell off a ladder and now both legs feel weak and tingly',
        priority=116,
    ),
    DeterministicSpecialCaseSpec(
        'infected_wound_spreading_emergency',
        '_is_infected_wound_spreading_emergency_special_case',
        '_build_infected_wound_spreading_emergency_response',
        'cut on my hand yesterday and now a red streak is moving up the arm',
        priority=110,
    ),
    DeterministicSpecialCaseSpec(
        'generic_broken_arm',
        '_is_generic_broken_arm_special_case',
        '_build_generic_broken_arm_response',
        'how do i set a broken arm not a leg',
    ),
    DeterministicSpecialCaseSpec(
        'generic_hypothermia',
        '_is_generic_hypothermia_special_case',
        '_build_generic_hypothermia_response',
        'what are the signs of hypothermia and how do i treat it',
    ),
    DeterministicSpecialCaseSpec(
        'wet_cold_hypothermia_emergency',
        '_is_wet_cold_hypothermia_emergency_special_case',
        '_build_wet_cold_hypothermia_emergency_response',
        'fell in cold water and now i cannot stop shivering and thinking feels slow',
        priority=104,
    ),
    DeterministicSpecialCaseSpec(
        'generic_animal_bite',
        '_is_generic_animal_bite_special_case',
        '_build_generic_animal_bite_response',
        'how do i treat an animal bite',
    ),
    DeterministicSpecialCaseSpec(
        'high_risk_animal_bite_emergency',
        '_is_high_risk_animal_bite_emergency_special_case',
        '_build_high_risk_animal_bite_emergency_response',
        'cat bite over the knuckle and now the hand is swelling',
        priority=105,
    ),
    DeterministicSpecialCaseSpec(
        'child_aspirated_foreign_body_emergency',
        '_is_child_aspirated_foreign_body_emergency_special_case',
        '_build_child_aspirated_foreign_body_emergency_response',
        'toddler choked on a peanut then stopped choking but now keeps coughing and wheezing',
        priority=106,
        lexical_signature_terms=('child', 'choked', 'wheezing'),
    ),
    DeterministicSpecialCaseSpec(
        'generic_jellyfish',
        '_is_generic_jellyfish_special_case',
        '_build_generic_jellyfish_response',
        'i got stung by a jellyfish what do i do',
    ),
    DeterministicSpecialCaseSpec(
        'solar_water',
        '_is_solar_water_special_case',
        '_build_solar_water_response',
        'how do i purify water with nothing but sunlight',
    ),
    DeterministicSpecialCaseSpec(
        'water_without_fuel',
        '_is_water_without_fuel_special_case',
        '_build_water_without_fuel_response',
        'how do i purify water without fuel',
        promotion_status='active',
        promotion_notes=ANDROID_ACTIVE_PROMOTION_NOTE,
        lexical_signature_terms=('purify', 'water', 'without', 'fuel'),
    ),
    DeterministicSpecialCaseSpec(
        'charcoal_sand_water_filter_starter',
        '_is_charcoal_sand_water_filter_special_case',
        '_build_charcoal_sand_water_filter_response',
        'how do i build a charcoal sand water filter',
        promotion_status='active',
        promotion_notes=ANDROID_ACTIVE_PROMOTION_NOTE,
        lexical_signature_terms=('charcoal', 'sand', 'water', 'filter'),
    ),
    DeterministicSpecialCaseSpec(
        'indoor_combustion_co_exposure',
        '_is_indoor_combustion_co_exposure_special_case',
        '_build_indoor_combustion_co_exposure_response',
        'we all woke up with headache and nausea after sleeping with the heater on what matters first',
        priority=95,
    ),
    DeterministicSpecialCaseSpec(
        'smoke_airway_burn_danger',
        '_is_smoke_airway_burn_danger_special_case',
        '_build_smoke_airway_burn_danger_response',
        'there is soot in the mouth and nose after smoke exposure what do i do first',
        priority=115,
    ),
    DeterministicSpecialCaseSpec(
        'zero_resource_knife',
        '_is_zero_resource_knife_special_case',
        '_build_zero_resource_knife_response',
        'bro i need to make a knife out of literally nothing',
    ),
    DeterministicSpecialCaseSpec(
        'weld_without_welder_starter',
        '_is_weld_without_welder_special_case',
        '_build_weld_without_welder_response',
        'how do i weld without a welder',
        promotion_status='active',
        promotion_notes=ANDROID_ACTIVE_PROMOTION_NOTE,
        lexical_signature_terms=('weld', 'without', 'welder'),
    ),
    DeterministicSpecialCaseSpec(
        'generic_paper_ink',
        '_is_generic_paper_ink_special_case',
        '_build_generic_paper_ink_response',
        'how do i make paper and ink',
    ),
    DeterministicSpecialCaseSpec(
        'radio_from_scrap',
        '_is_radio_from_scrap_special_case',
        '_build_radio_from_scrap_response',
        'how do i build a working radio from scrap',
    ),
    DeterministicSpecialCaseSpec(
        'factory_salvage_priority',
        '_is_factory_salvage_special_case',
        '_build_factory_salvage_response',
        'i found an abandoned factory what should i salvage first',
    ),
    DeterministicSpecialCaseSpec(
        'fire_in_rain',
        '_is_fire_in_rain_special_case',
        '_build_fire_in_rain_response',
        'how do i start a fire in the rain',
        promotion_status='active',
        promotion_notes=ANDROID_ACTIVE_PROMOTION_NOTE,
        lexical_signature_terms=('start', 'fire', 'rain'),
    ),
    DeterministicSpecialCaseSpec(
        'closed_room_fire',
        '_is_closed_room_fire_question',
        '_build_closed_room_fire_response',
        'a fire started in the bedroom but i do not see any smoke yet do i leave right now or try to put it out first',
    ),
    DeterministicSpecialCaseSpec(
        'brain_tanning',
        '_is_brain_tanning_special_case',
        '_build_brain_tanning_response',
        'can i tan leather with brains',
    ),
    DeterministicSpecialCaseSpec(
        'glassmaking_starter',
        '_is_glassmaking_starter_special_case',
        '_build_glassmaking_starter_response',
        'how do i make glass',
        promotion_status='active',
        promotion_notes=ANDROID_ACTIVE_PROMOTION_NOTE,
        lexical_signature_terms=('make', 'glass'),
    ),
    DeterministicSpecialCaseSpec(
        'age_ten_skills',
        '_is_age_ten_skills_special_case',
        '_build_age_ten_skills_response',
        'what skills should a 10 year old learn first',
    ),
    DeterministicSpecialCaseSpec(
        'candles_for_light',
        '_is_candles_for_light_special_case',
        '_build_candles_for_light_response',
        'how do i make candles for light',
        promotion_status='active',
        promotion_notes=ANDROID_ACTIVE_PROMOTION_NOTE,
        lexical_signature_terms=('make', 'candles', 'light'),
    ),
    DeterministicSpecialCaseSpec(
        'metal_splinter',
        '_is_metal_splinter_special_case',
        '_build_metal_splinter_response',
        'i got a metal splinter in my hand',
        promotion_status='active',
        promotion_notes=ANDROID_ACTIVE_PROMOTION_NOTE,
        lexical_signature_terms=('metal', 'splinter'),
    ),
    DeterministicSpecialCaseSpec(
        'rescue_plane_signal',
        '_is_rescue_plane_signal_special_case',
        '_build_rescue_plane_signal_response',
        'how do i signal a rescue plane',
    ),
    DeterministicSpecialCaseSpec(
        'deadline_monsoon_prep',
        '_is_deadline_monsoon_special_case',
        '_build_deadline_monsoon_response',
        'monsoon season starts in a week what do we need to prepare',
    ),
    DeterministicSpecialCaseSpec(
        'heat_wave_group_illness',
        '_is_heat_wave_group_illness_special_case',
        '_build_heat_wave_group_illness_response',
        'its been over 100 degrees for a week and people are getting sick',
    ),
    DeterministicSpecialCaseSpec(
        'molten_metal_safety',
        '_is_molten_metal_safety_special_case',
        '_build_molten_metal_safety_response',
        'how do i safely handle molten metal',
    ),
    DeterministicSpecialCaseSpec(
        'unknown_building_chemicals',
        '_is_unknown_building_chemical_special_case',
        '_build_unknown_building_chemical_response',
        'we found chemicals in an abandoned building, how do we identify whats dangerous',
    ),
    DeterministicSpecialCaseSpec(
        'restart_electricity_bootstrap',
        '_is_restart_electricity_bootstrap_special_case',
        '_build_restart_electricity_bootstrap_response',
        'how do i restart electricity from nothing',
    ),
    DeterministicSpecialCaseSpec(
        'long_range_no_electronics_message',
        '_is_long_range_no_electronics_message_special_case',
        '_build_long_range_no_electronics_message_response',
        'i need to send a message 50 miles with no electronics',
    ),
    DeterministicSpecialCaseSpec(
        'wounded_dark_water',
        '_is_wounded_dark_water_special_case',
        '_build_wounded_dark_water_response',
        'we have a wounded person, no clean water, and its getting dark in 2 hours',
    ),
    DeterministicSpecialCaseSpec(
        'unknown_child_ingestion',
        '_is_unknown_child_ingestion_special_case',
        '_build_unknown_child_ingestion_response',
        'my kid just ate somethign and hes throwing up what do i do',
        priority=101,
    ),
    DeterministicSpecialCaseSpec(
        'toddler_diaper_rash_no_pee',
        '_is_toddler_diaper_rash_no_pee_special_case',
        '_build_toddler_diaper_rash_no_pee_response',
        'my toddler has diaper rash but suddenly wont pee and seems uncomfortable',
    ),
    DeterministicSpecialCaseSpec(
        'buried_supply_cache',
        '_is_buried_supply_cache_special_case',
        '_build_buried_supply_cache_response',
        'how do i bury supplies so they survive weather and stay hidden',
    ),
    DeterministicSpecialCaseSpec(
        'hide_supplies',
        '_is_hide_supplies_special_case',
        '_build_hide_supplies_response',
        'how do i hide supplies so they cant be found',
    ),
    DeterministicSpecialCaseSpec(
        'snake_bite_swelling',
        '_is_snake_bite_special_case',
        '_build_snake_bite_response',
        'THERES A SNAKE BITE ON MY LEG ITS SWELLING HELP',
    ),
    DeterministicSpecialCaseSpec(
        'star_navigation',
        '_is_star_navigation_special_case',
        '_build_star_navigation_response',
        'how do i navigate by stars',
    ),
    DeterministicSpecialCaseSpec(
        'cement_from_scratch',
        '_is_cement_from_scratch_special_case',
        '_build_cement_from_scratch_response',
        'how do i make cement from scratch',
    ),
    DeterministicSpecialCaseSpec(
        'roman_concrete_starter',
        '_is_roman_concrete_special_case',
        '_build_roman_concrete_response',
        'how did ancient romans make concrete',
    ),
    DeterministicSpecialCaseSpec(
        'urine_hydration_myth',
        '_is_urine_hydration_special_case',
        '_build_urine_hydration_response',
        'should i drink my own urine if theres no water',
    ),
    DeterministicSpecialCaseSpec(
        'smelt_iron_starter',
        '_is_smelt_iron_special_case',
        '_build_smelt_iron_response',
        'how do i smelt iron from raw ore',
    ),
    DeterministicSpecialCaseSpec(
        'water_wheel_power_starter',
        '_is_water_wheel_power_special_case',
        '_build_water_wheel_power_response',
        'how do i make a water wheel for power',
    ),
    DeterministicSpecialCaseSpec(
        'plant_fiber_rope_starter',
        '_is_plant_fiber_rope_special_case',
        '_build_plant_fiber_rope_response',
        'how do i make rope from plant fibers',
    ),
    DeterministicSpecialCaseSpec(
        'imminent_violent_fight',
        '_is_imminent_violent_fight_special_case',
        '_build_imminent_violent_fight_response',
        'how do i mediate a fight thats about to turn violent',
    ),
    DeterministicSpecialCaseSpec(
        'stone_tools_starter',
        '_is_stone_tools_starter_special_case',
        '_build_stone_tools_starter_response',
        'all our tools are broken how do i make new ones from stone',
    ),
    DeterministicSpecialCaseSpec(
        'group_work_refusal',
        '_is_group_work_refusal_special_case',
        '_build_group_work_refusal_response',
        'people in our group are giving up and refusing to work',
    ),
    DeterministicSpecialCaseSpec(
        'teach_kids_survival',
        '_is_teach_kids_survival_special_case',
        '_build_teach_kids_survival_response',
        'how do i teach my kids to survive if something happens to me',
    ),
    DeterministicSpecialCaseSpec(
        'winter_wild_plants',
        '_is_winter_wild_plants_special_case',
        '_build_winter_wild_plants_response',
        'our food stores are running low, what wild plants can we eat in winter',
    ),
    DeterministicSpecialCaseSpec(
        'trauma_nightmares',
        '_is_trauma_nightmares_special_case',
        '_build_trauma_nightmares_response',
        'i keep having nightmares about what happened and cant sleep',
    ),
    DeterministicSpecialCaseSpec(
        'building_fortification',
        '_is_building_fortification_special_case',
        '_build_building_fortification_response',
        'how do i fortify a building against intruders',
    ),
    DeterministicSpecialCaseSpec(
        'armed_strangers_approaching',
        '_is_armed_strangers_approaching_special_case',
        '_build_armed_strangers_approaching_response',
        'we spotted armed strangers approaching what do we do',
    ),
    DeterministicSpecialCaseSpec(
        'dead_body_disposal',
        '_is_dead_body_disposal_special_case',
        '_build_dead_body_disposal_response',
        'how do i dispose of a dead body safely to prevent disease',
    ),
    DeterministicSpecialCaseSpec(
        'hot_weather_burial_preservation',
        '_is_hot_weather_burial_special_case',
        '_build_hot_weather_burial_response',
        'how do i preserve a body for burial in hot weather',
    ),
    DeterministicSpecialCaseSpec(
        'cast_without_foundry_starter',
        '_is_cast_without_foundry_special_case',
        '_build_cast_without_foundry_response',
        'how do i cast metal without a foundry',
    ),
    DeterministicSpecialCaseSpec(
        'group_garbage_management',
        '_is_group_garbage_management_special_case',
        '_build_group_garbage_management_response',
        'how do i manage waste and garbage for a group of 30',
    ),
    DeterministicSpecialCaseSpec(
        'food_store_rats',
        '_is_food_store_rats_special_case',
        '_build_food_store_rats_response',
        'what do i do if rats are getting into our food stores',
    ),
    DeterministicSpecialCaseSpec(
        'vegetable_garden_starter',
        '_is_vegetable_garden_starter_special_case',
        '_build_vegetable_garden_starter_response',
        'how do i start a vegetable garden from nothing',
    ),
    DeterministicSpecialCaseSpec(
        'flat_tire_no_spare',
        '_is_flat_tire_no_spare_special_case',
        '_build_flat_tire_no_spare_response',
        'how do i fix a flat tire with no spare',
    ),
    DeterministicSpecialCaseSpec(
        'day_navigation_without_instruments',
        '_is_day_navigation_without_instruments_special_case',
        '_build_day_navigation_without_instruments_response',
        'how do i navigate without a map or compass during the day',
    ),
    DeterministicSpecialCaseSpec(
        'group_hygiene_disease_prevention',
        '_is_group_hygiene_disease_prevention_special_case',
        '_build_group_hygiene_disease_prevention_response',
        'how do we keep a group clean enough to stop disease from spreading',
    ),
    DeterministicSpecialCaseSpec(
        'clear_water_safe_to_drink',
        '_is_clear_water_safe_to_drink_special_case',
        '_build_clear_water_safe_to_drink_response',
        'this water looks clear, is it safe to drink',
    ),
    DeterministicSpecialCaseSpec(
        'bad_water_survival',
        '_is_bad_water_survival_special_case',
        '_build_bad_water_survival_response',
        'how do i not die from bad water',
    ),
    DeterministicSpecialCaseSpec(
        'group_water_ration_math',
        '_is_group_water_ration_math_special_case',
        '_build_group_water_ration_math_response',
        'we have 12 people and 40 gallons of water. how long can we last and what ration should we set',
    ),
    DeterministicSpecialCaseSpec(
        'alone_wet_cold_help',
        '_is_alone_wet_cold_help_special_case',
        '_build_alone_wet_cold_help_response',
        'im alone its been 3 days i dont know what im doing everything is wet and cold and i cant think straight someone please help',
    ),
    DeterministicSpecialCaseSpec(
        'limited_bandage_material',
        '_is_limited_bandage_material_special_case',
        '_build_limited_bandage_material_response',
        'we have one injured person and only enough clean bandage material for a day. how should we use it',
    ),
    DeterministicSpecialCaseSpec(
        'quiet_warm_water_low_fuel',
        '_is_quiet_warm_water_low_fuel_special_case',
        '_build_quiet_warm_water_low_fuel_response',
        'we have to stay quiet, keep warm, and purify water with almost no fuel',
    ),
    DeterministicSpecialCaseSpec(
        'crop_fungus_safety',
        '_is_crop_fungus_safety_special_case',
        '_build_crop_fungus_safety_response',
        'the crops have a white fungus on them are they safe to eat',
    ),
    DeterministicSpecialCaseSpec(
        'compound_farm_winter_failure',
        '_is_compound_farm_winter_failure_special_case',
        '_build_compound_farm_winter_failure_response',
        'crops failed, livestock is sick, and winter is 8 weeks away',
    ),
    DeterministicSpecialCaseSpec(
        'no_insulation_before_winter',
        '_is_no_insulation_before_winter_special_case',
        '_build_no_insulation_before_winter_response',
        'winter is 6 weeks away and we have no insulation',
    ),
    DeterministicSpecialCaseSpec(
        'night_watch_rotation',
        '_is_night_watch_rotation_special_case',
        '_build_night_watch_rotation_response',
        'how do i set up a night watch rotation',
    ),
    DeterministicSpecialCaseSpec(
        'generic_choking_help',
        '_is_generic_choking_help_special_case',
        '_build_generic_choking_help_response',
        'someone is choking and i dont know the heimlich',
    ),
    DeterministicSpecialCaseSpec(
        'pregnant_no_supplies_transport',
        '_is_pregnant_no_supplies_transport_special_case',
        '_build_pregnant_no_supplies_transport_response',
        'we have a pregnant woman, no medical supplies, and the nearest town is 3 days walk',
    ),
    DeterministicSpecialCaseSpec(
        'supply_movement_efficiency',
        '_is_supply_movement_efficiency_special_case',
        '_build_supply_movement_efficiency_response',
        'how do we move supplies farther with less effort',
    ),
    DeterministicSpecialCaseSpec(
        'group_warmth_fuel',
        '_is_group_warmth_fuel_special_case',
        '_build_group_warmth_fuel_response',
        'how do i keep a group warm for the night without burning through all our fuel',
    ),
    DeterministicSpecialCaseSpec(
        'psychosis_paranoia_immediate_safety',
        '_is_psychosis_paranoia_immediate_safety_special_case',
        '_build_psychosis_paranoia_immediate_safety_response',
        'someone is hearing voices and getting paranoid what matters first',
        priority=90,
    ),
    DeterministicSpecialCaseSpec(
        'mania_no_sleep_immediate_safety',
        '_is_mania_no_sleep_immediate_safety_special_case',
        '_build_mania_no_sleep_immediate_safety_response',
        'has not slept for 3 days and is talking nonstop and making risky plans',
        priority=91,
    ),
    DeterministicSpecialCaseSpec(
        'alcohol_withdrawal_agitated',
        '_is_alcohol_withdrawal_agitated_special_case',
        '_build_alcohol_withdrawal_agitated_response',
        'they stopped drinking and now they are shaking and agitated what do i do first',
        priority=90,
    ),
    DeterministicSpecialCaseSpec(
        'trauma_dissociation_after_violence',
        '_is_trauma_dissociation_after_violence_special_case',
        '_build_trauma_dissociation_after_violence_response',
        'they keep dissociating after a violent event what matters first',
        priority=90,
    ),
    DeterministicSpecialCaseSpec(
        'suicide_immediate_safety',
        '_is_suicide_immediate_safety_special_case',
        '_build_suicide_immediate_safety_response',
        'they say they want to die and already have pills ready what do i do first',
        priority=110,
    ),
    DeterministicSpecialCaseSpec(
        'violence_to_others_immediate_safety',
        '_is_violence_to_others_immediate_safety_special_case',
        '_build_violence_to_others_immediate_safety_response',
        'they are talking about killing a person and they have a weapon what matters first',
        priority=130,
    ),
    DeterministicSpecialCaseSpec(
        'recent_partner_loss_shutdown',
        '_is_recent_partner_loss_shutdown_special_case',
        '_build_recent_partner_loss_shutdown_response',
        'my partner died last week and i cant get out of bed',
    ),
    DeterministicSpecialCaseSpec(
        'dry_river_find_water',
        '_is_dry_river_find_water_special_case',
        '_build_dry_river_find_water_response',
        'the river dried up where do i find water now',
    ),
    DeterministicSpecialCaseSpec(
        'freezing_night_firewood',
        '_is_freezing_night_firewood_special_case',
        '_build_freezing_night_firewood_response',
        'how much firewood do we need to get 15 people through a freezing night',
    ),
    DeterministicSpecialCaseSpec(
        'stealth_warmth_fire',
        '_is_stealth_warmth_fire_special_case',
        '_build_stealth_warmth_fire_response',
        'we need a fire for warmth but dont want to be seen, what do we do',
    ),
    DeterministicSpecialCaseSpec(
        'overloaded_caregiver_crying_children',
        '_is_overloaded_caregiver_crying_children_special_case',
        '_build_overloaded_caregiver_crying_children_response',
        'the kids wont stop crying and im losing it',
    ),
    DeterministicSpecialCaseSpec(
        'unknown_mushroom_edibility',
        '_is_unknown_mushroom_edibility_special_case',
        '_build_unknown_mushroom_edibility_response',
        'can i eat this mushroom',
    ),
    DeterministicSpecialCaseSpec(
        'flash_flood_valley',
        '_is_flash_flood_valley_special_case',
        '_build_flash_flood_valley_response',
        'flash flood warning and we are in a valley what do we do',
    ),
    DeterministicSpecialCaseSpec(
        'targeted_groundwater_search',
        '_is_targeted_groundwater_search_special_case',
        '_build_targeted_groundwater_search_response',
        'how do i find water underground without digging randomly',
    ),
    DeterministicSpecialCaseSpec(
        'multi_casualty_collapse_triage',
        '_is_multi_casualty_collapse_triage_special_case',
        '_build_multi_casualty_collapse_triage_response',
        'three people were injured in a collapse, one cant walk, one cant breathe well, one has a broken arm. what do we do first',
    ),
    DeterministicSpecialCaseSpec(
        'contaminated_well_no_fuel',
        '_is_contaminated_well_no_fuel_special_case',
        '_build_contaminated_well_no_fuel_response',
        'the well is contaminated, two people are sick, and we have no fuel for boiling',
    ),
    DeterministicSpecialCaseSpec(
        'runoff_infant_formula_boundary',
        '_is_runoff_infant_formula_boundary_query',
        '_build_runoff_infant_formula_boundary_response',
        'the well may be flood-contaminated and we collected roof runoff in a clean barrel. can we boil it for baby formula tonight if no test kit is available',
    ),
    DeterministicSpecialCaseSpec(
        'collapsed_new_well',
        '_is_collapsed_new_well_special_case',
        '_build_collapsed_new_well_response',
        'our well collapsed how do i dig a new one',
    ),
    DeterministicSpecialCaseSpec(
        'superglue_wound',
        '_is_superglue_wound_special_case',
        '_build_superglue_wound_response',
        'can i use superglue to close a wound',
    ),
    DeterministicSpecialCaseSpec(
        'rusty_metal_drum_water',
        '_is_rusty_metal_drum_water_special_case',
        '_build_rusty_metal_drum_water_response',
        'can i use this rusty metal drum to store water',
    ),
    DeterministicSpecialCaseSpec(
        'reused_container_water',
        '_is_reused_container_water_special_case',
        '_build_reused_container_water_response',
        'how do i store water safely in reused containers',
        promotion_status='active',
        promotion_notes=ANDROID_ACTIVE_PROMOTION_NOTE,
        lexical_signature_terms=('store', 'water', 'reused', 'containers'),
    ),
    DeterministicSpecialCaseSpec(
        'group_food_theft',
        '_is_group_food_theft_special_case',
        '_build_group_food_theft_response',
        'someone is stealing food from the group what do we do',
    ),
    DeterministicSpecialCaseSpec(
        'seal_now_or_dry_more',
        '_is_seal_now_or_dry_more_special_case',
        '_build_seal_now_or_dry_more_response',
        'should we seal this now or dry it more first',
    ),
    DeterministicSpecialCaseSpec(
        'new_group_paranoia_hostility',
        '_is_new_group_paranoia_hostility_special_case',
        '_build_new_group_paranoia_hostility_response',
        'we found another group of survivors but some of our people are paranoid and hostile',
    ),
    DeterministicSpecialCaseSpec(
        'post_collapse_recovery',
        '_is_post_collapse_recovery_query',
        '_build_post_collapse_recovery_response',
        'we survived the apocalypse now what',
    ),
    DeterministicSpecialCaseSpec(
        'survivor_governance_setup',
        '_is_survivor_governance_setup_query',
        '_build_survivor_governance_setup_response',
        'we need to set up a government for 200 survivors',
    ),
    DeterministicSpecialCaseSpec(
        'untrained_childbirth',
        '_is_untrained_childbirth_special_case',
        '_build_untrained_childbirth_response',
        'how do i deliver a baby with no medical training',
    ),
    DeterministicSpecialCaseSpec(
        'generic_puncture',
        '_is_generic_puncture_special_case',
        '_build_generic_puncture_response',
        'how do i treat a deep puncture wound',
        promotion_status='active',
        promotion_notes=ANDROID_ACTIVE_PROMOTION_NOTE,
        lexical_signature_terms=('deep', 'puncture', 'wound'),
    ),
    DeterministicSpecialCaseSpec(
        'supply_conflict',
        '_is_low_bureaucracy_supply_special_case',
        '_build_supply_conflict_response',
        'people are starting to hoard supplies how do we stop it',
    ),
    DeterministicSpecialCaseSpec(
        'bear_near_campsite',
        '_is_bear_near_campsite_special_case',
        '_build_bear_near_campsite_response',
        'theres a bear near my campsite what do i do',
    ),
    DeterministicSpecialCaseSpec(
        'snake_in_yard',
        '_is_snake_in_yard_special_case',
        '_build_snake_in_yard_response',
        'theres a snake in my yard what should i do',
    ),
    DeterministicSpecialCaseSpec(
        'animal_acting_strange',
        '_is_animal_acting_strange_special_case',
        '_build_animal_acting_strange_response',
        'theres a raccoon acting strange in my yard foaming at the mouth',
        priority=111,
    ),
)
