(() => {
  const domIds = {
    healthBadge: 'healthBadge',
    healthText: 'healthText',
    refreshToggle: 'refreshToggle',
    stateFilter: 'stateFilter',
    searchBox: 'searchBox',
    taskCount: 'taskCount',
    runningCount: 'runningCount',
    taskList: 'taskList',
    taskListEmptyState: 'taskListEmptyState',
    taskListError: 'taskListError',
    selectedTaskHeader: 'selectedTaskHeader',
    selectedTaskMeta: 'selectedTaskMeta',
    detailErrorState: 'detailErrorState',
    detailEmptyState: 'detailEmptyState',
    detailContent: 'detailContent',
    selectedTaskState: 'selectedTaskState',
    selectedTaskUpdated: 'selectedTaskUpdated',
    selectedTaskCreated: 'selectedTaskCreated',
    selectedTaskSubmissions: 'selectedTaskSubmissions',
    selectedTaskProvider: 'selectedTaskProvider',
    selectedTaskModel: 'selectedTaskModel',
    selectedTaskAbortRequested: 'selectedTaskAbortRequested',
    selectedTaskLastError: 'selectedTaskLastError',
    resultLatestText: 'resultLatestText',
    resultFinalText: 'resultFinalText',
    taskJson: 'taskJson',
    resultJson: 'resultJson',
    finalResultJson: 'finalResultJson',
    taskPaths: 'taskPaths',
    lastRefresh: 'lastRefresh',
    lastRefreshError: 'lastRefreshError',
    bridgeUrl: 'bridgeUrl',
    viewerError: 'viewerError',
    refreshButton: 'refreshButton',
  };

  window.SidecarViewerContract = {
    bridge: {
      baseUrl: `${window.location.origin}/api`,
      streamBaseUrl: 'http://127.0.0.1:4317',
      pollIntervalMs: 5000,
      streamPollMs: 3000,
      listLimit: 200,
      runningStates: ['busy', 'submitted', 'queued'],
      staleThresholdMs: 15 * 60 * 1000,
    },
    domIds,
  };
})();
